<?php
// Database configuration - Auto-generated by deployment script
// This file should be included before using DatabaseService

putenv('DB_HOST=__DB_ENDPOINT__');
putenv('DB_NAME=__DB_NAME__');
putenv('DB_USER=__DB_USERNAME__');
putenv('DB_PASS=__DB_PASSWORD__');

// Also set $_ENV for compatibility
$_ENV['DB_HOST'] = '__DB_ENDPOINT__';
$_ENV['DB_NAME'] = '__DB_NAME__';
$_ENV['DB_USER'] = '__DB_USERNAME__';
$_ENV['DB_PASS'] = '__DB_PASSWORD__';
?>
